# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedform', '0003_auto_20171001_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
