# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedform', '0004_auto_20171001_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='neighbourhood',
            field=models.CharField(choices=[('nairobi', 'nairobi'), ('westlands', 'westlands'), ('langata', 'langata'), ('muthaiga', 'muthaiga'), ('thika', 'thika')], max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
